name: mega_commons
description: Commons package for flutter mega modules.
version: 1.7.0
homepage: https://megaleios.com
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  ansicolor: ^2.0.1
  flutter:
    sdk: flutter
  logger: ^2.5.0
  restart_app: ^1.2.1
  diacritic: ^0.1.4
  flutter_svg: ^2.0.10+1
  mega_commons_dependencies:
  flutter_alice: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.3

dependency_overrides:
  mega_commons_dependencies:
    #   git:
    #     url: git@github.com:megaleios-git/megaflutter_commons_dependencies.git
    #     ref: 1.7.0
    path: ../mega_commons_dependencies

flutter:
  assets:
    - assets/
